name: Docker Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and test
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: app:test
          target: test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build production image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: app:prod
          target: production
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Optional: Push to ECR
      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1
      #
      # - name: Push to Amazon ECR
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: your-repo-name
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     docker tag app:prod $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # Optional: Deploy to ECS
      # - name: Deploy to ECS
      #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      #   with:
      #     task-definition: task-definition.json
      #     service: your-service-name
      #     cluster: your-cluster-name
      #     wait-for-service-stability: true
